// Cognee knowledge-graph client (Cognee Cloud REST API, X-Api-Key auth). Saathi uses it for retrieval and
// grounded answers only; every caller has a local fallback, and no calculation depends on its output.
import { cogneeAvailable, settings } from './config';
import { providers } from './integrations';

export class CogneeError extends Error {}

export interface KnowledgeEntry {
  id: string;
  kind: 'policy_clause' | 'regulation' | 'guide' | 'playbook';
  title: string;
  document: string;
  text: string;
  clause_id?: string;
  page?: number;
}

export interface KnowledgeHit {
  entry_id: string | null;
  kind: string | null;
  title: string | null;
  document: string | null;
  clause_id: string | null;
  page: number | null;
  text: string;
}

// Each entry is stored with a header line so search results can be cited back to their source.
export function entryText(entry: KnowledgeEntry): string {
  const tag = [entry.id, entry.kind, entry.clause_id ? `clause ${entry.clause_id}` : '', entry.page ? `page ${entry.page}` : '', entry.document]
    .filter(Boolean)
    .join(' | ');
  return `[${tag}] ${entry.title}. ${entry.text}`;
}

export function parseHit(text: string): KnowledgeHit {
  const match = /^\[([^\]]+)\]\s*([^.]*)\.\s*([\s\S]*)$/.exec(text.trim());
  if (!match) return { entry_id: null, kind: null, title: null, document: null, clause_id: null, page: null, text: text.trim() };
  const parts = match[1]!.split(' | ');
  const clause = parts.find((part) => part.startsWith('clause '));
  const page = parts.find((part) => part.startsWith('page '));
  return {
    entry_id: parts[0] ?? null,
    kind: parts[1] ?? null,
    title: match[2]!.trim() || null,
    document: parts.at(-1) ?? null,
    clause_id: clause ? clause.slice(7) : null,
    page: page ? Number(page.slice(5)) : null,
    text: match[3]!.trim(),
  };
}

async function request<T>(method: 'GET' | 'POST', path: string, body?: unknown, timeoutMs = 20_000): Promise<T> {
  if (!cogneeAvailable()) throw new CogneeError('Cognee is disabled or not configured.');
  let response: Response;
  try {
    response = await providers.fetch(`${settings.cogneeBaseUrl}${path}`, {
      method,
      headers: { 'X-Api-Key': settings.cogneeApiKey, 'content-type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: AbortSignal.timeout(timeoutMs),
    });
  } catch (error) {
    throw new CogneeError(`Cognee is unreachable: ${error instanceof Error ? error.message : 'unknown error'}`);
  }
  const text = await response.text();
  if (!response.ok) throw new CogneeError(`Cognee ${path} returned ${response.status}: ${text.slice(0, 200)}`);
  return (text ? JSON.parse(text) : null) as T;
}

export async function addTexts(dataset: string, texts: string[]): Promise<{ dataset_id: string | null }> {
  const result = await request<{ dataset_id?: string }>('POST', '/api/v1/add_text', { datasetName: dataset, textData: texts }, 60_000);
  return { dataset_id: result?.dataset_id ?? null };
}

export async function cognify(dataset: string): Promise<void> {
  await request('POST', '/api/v1/cognify', { datasets: [dataset] }, 60_000);
}

export async function datasetReady(datasetId: string): Promise<boolean> {
  const status = await request<Record<string, string>>('GET', `/api/v1/datasets/status?dataset=${encodeURIComponent(datasetId)}`);
  return /COMPLETED/i.test(String(status?.[datasetId] ?? ''));
}

// Chunk search: returns the stored entry texts, parsed back into cited hits.
export async function searchChunks(query: string, datasets: string[], topK = 4): Promise<KnowledgeHit[]> {
  const results = await request<{ search_result: unknown }[]>('POST', '/api/v1/search', { query, searchType: 'CHUNKS', datasets, topK }, 15_000);
  const hits: KnowledgeHit[] = [];
  for (const result of results ?? []) {
    for (const chunk of Array.isArray(result.search_result) ? result.search_result : []) {
      const text = typeof chunk === 'string' ? chunk : String((chunk as { text?: unknown }).text ?? '');
      if (text.trim()) hits.push(parseHit(text));
    }
  }
  return hits.slice(0, topK);
}

// Graph completion: a short grounded answer generated by Cognee over the knowledge graph.
export async function graphAnswer(query: string, datasets: string[]): Promise<string | null> {
  const results = await request<{ search_result: unknown }[]>(
    'POST',
    '/api/v1/search',
    {
      query,
      searchType: 'GRAPH_COMPLETION',
      datasets,
      topK: 6,
      systemPrompt:
        'Answer in at most 90 words using only the knowledge provided. Give general guidance, not a decision on the person\'s case. If the knowledge does not cover the question, say so.',
    },
    25_000,
  );
  const first = results?.[0]?.search_result;
  const answer = Array.isArray(first) ? first.find((item) => typeof item === 'string') : typeof first === 'string' ? first : null;
  return typeof answer === 'string' && answer.trim() ? plainText(answer) : null;
}

// Chat bubbles show plain text: drop markdown emphasis, headings, and list markers.
export function plainText(markdown: string): string {
  return markdown
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/(^|\s)[*_](\S.*?)[*_](?=\s|$)/g, '$1$2')
    .replace(/^#+\s*/gm, '')
    .replace(/^\s*[-*•]\s+/gm, '• ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}
