[theme]
base = "light"
primaryColor = "#00B9E8"
backgroundColor = "#F2F6FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#10264B"
borderColor = "#D8E2EF"
showWidgetBorder = true
baseRadius = "large"
buttonRadius = "large"
headingFont = "serif"

[theme.sidebar]
backgroundColor = "#10264B"
secondaryBackgroundColor = "#17345E"
textColor = "#F5F8FC"
primaryColor = "#00B9E8"
borderColor = "#28466D"
